### ISSUE TITLE
Schedule

### ISSUE THREAD

**Issue by Leofuchs200811** [neatnik/terminal.land#130]
Hello, is there a server that stays connected most of the time or, if there is only [Terminal Land](terminal.land), what time does the server stay connected? Or, is it my PC that needs to be connected to the server, or, if I can do something to connect, what can I do?

**Comment by newbold** [comment]
Hi! The connection actually takes place at login, so as soon as you log in you'll be connected. If you can send an email to support@terminal.land, I can help you get registered and logged in. 👍☺️
