### ISSUE TITLE
Integrate Alles ID for avatar usage

### ISSUE THREAD

**Issue by newbold** [neatnik/terminal.land#28]
> set my avatar [alles user id]

https://avatar.alles.cc/allesuserid

**Comment by newbold** [comment]
From Archie:

> also if you wanted you could make it slightly easier so instead of putting in the id you could just do set my alles Archie Baer#0001, then fetch the id using https://horizon.alles.cc/nametag?name=Archie%20Baer&tag=0001, but that'd be more work lol

**Comment by adrianbaumgart** [comment]
Another option would be to use [QuickAuth](https://github.com/alleshq/quickauth). I don't know if that would be too complicated but with QuickAuth, you can get the user id while verifying that the user doesn't enter a random id/name.

**Comment by archiecodes** [comment]
Yeah, and you could use it as an optional authentication method

**Comment by k1l0b1t** [comment]
Yeah, "log in with alles"

**Comment by newbold** [comment]
QuickAuth is implemented! (try `set my allesid`, then log out, and then `login [username]`). And avatars are now displayed on the Compendium person pages for anyone who has set an AllesID. Woot!

**Comment by newbold** [comment]
Alles integration has been removed. Looking forward to implementing other authentication and avatar integrations with more established, stable entities.
