### ISSUE TITLE
Add neat.bot as help NPC

### ISSUE THREAD

**Issue by k1l0b1t** [neatnik/terminal.land#30]
Maybe use neatbot as help NPC. Would be nice

**Comment by newbold** [comment]
Love the idea! Will work on it. 😁

**Comment by newbold** [comment]
Working on an approach that will use incoming and outgoing webhooks to allow any NPC to be managed remotely. Incoming webhooks are nearly complete (just need to polish off the session management. Outgoing webhooks will need a little more work, as I'll need to create a way to define the kinds of events to which the NPC can subscribe. (Or something like that... still thinking it through.)

**Comment by newbold** [comment]
All done! Neatbot is now in the Lab:

> &gt; Neatbot, hello
> 
> Neatbot says (to you), “Hey there!”
> 
> &gt; Neatbot, what is a banana
> 
> Neatbot says (to you), “banana is edible fruit, and herb; banana is related to banana.”

(Nobody ever said Neatbot was very smart.)
