### ISSUE TITLE
Implement login with Alles QuickAuth

### ISSUE THREAD

**Issue by newbold** [neatnik/terminal.land#48]

**Comment by newbold** [comment]
QuickAuth is working! Get it going with:

> &gt; set my allesid

However, still need to do these two things:

1. Show a confirmation that the setup is complete
2. Remove the need to click the links (just trigger QuickAuth and redirect accordingly)

**Comment by newbold** [comment]
All set now.

**Comment by archiecodes** [comment]
Awesome!
