### ISSUE TITLE
Ignore markdown formatting when adding a "\" in front of it

### ISSUE THREAD

**Issue by leabmgrt** [neatnik/terminal.land#65]
In markdown, you can add a `\` in front of formatting characters (like `*` and `_`) so it doesn't format.

Example:

- With formatting: *hi* (`*hi*`)
- Ignore formatting: \*hi* (`\*hi*`)

**Comment by newbold** [comment]
This has been corrected (finally), along with some other Markdown improvements. Sorry for the delay!
