### ISSUE TITLE
Store typed text in the terminal without sending it

### ISSUE THREAD

**Issue by leabmgrt** [neatnik/terminal.land#66]
When you start typing a command (for example `give ...`) and then want to go up (with the arrow keys) the started command is gone. My idea is that it stores that command and adds it to the storage.

![demogif](https://user-images.githubusercontent.com/28984823/93000838-30d6be00-f52b-11ea-98a6-d17a6757349e.gif)

**Comment by newbold** [comment]
I've updated the buffer code to handle this more elegantly; now any input (submitted or not) should be preserved when moving upward into the buffer. Let me know if you run into any other weird issues with it, though. And thanks for reporting the issue!
